### ISSUE TITLE
hi ,i just get the error same as people who use unity3,can you help me!

### ISSUE THREAD

**Issue by wsdjeg** [NVentimiglia/Unity3d-Foundation#1]
https://github.com/gitskarios/GithubAndroidSdk/issues/28

**Comment by NVentimiglia** [comment]
what ?

**Comment by wsdjeg** [comment]
thank you for your reply,i have fixed it,it is due to conflict between apklib and jar

**Comment by wsdjeg** [comment]
maven android plugin just need apklib or arr dependency,but my javacomplete.vim plugin need jar,so i need to use provided scope
