### ISSUE TITLE
BindingContext has extra reflection

### ISSUE THREAD

**Issue by LeooooooK** [NVentimiglia/Unity3d-Foundation#14]
I guess this may be a problem.
It may also be that I'm stupid and I don't understand the intention of doing this.
![image](https://user-images.githubusercontent.com/11335956/39661960-6ea4d310-508d-11e8-9233-5bf280e0b06e.png)
DataType works only under the Editor in Mock mode, but there is no judgment of Runtime here.
I think it can be changed like this:
If (DataType == null&&!Application.isPlaying)

**Comment by NVentimiglia** [comment]
This library is no longer being maintained. 
Moving on to a proprietary in-house solution.
