### ISSUE TITLE
Updating the binding value when a GameObject is not active

### ISSUE THREAD

**Issue by Caiuse** [NVentimiglia/Unity3d-Foundation#9]
Hi There,

I keep running into the issues around data-bound field not updating when the GameObject on which they are attached is not active. Is there any work around to this or suggestions which will allow an inactive GameObject still receiving updates.

Example structure:
- Parent ( BindingContext & ViewModel )
- -- Child ( Inactive GO, ListBinder )

When the Child is inactive any changes the ObservableList on the ViewModel are not reflected.

Best Regards, Caius.

**Comment by NVentimiglia** [comment]
This is not currently supported as the BindingBase hooks into the OnEnable event.

https://github.com/NVentimiglia/Unity3d-Foundation/blob/master/Foundation/Assets/Foundation/Databinding/Observers/BindingBase.cs#L169

You can try changing this to Awake / OnDestroy

Alternatively you can add a "DoNotUnbindOnDisable" flag of some sorts

**Comment by Caiuse** [comment]
Thank you for your quick response to this. I think the "DoNotUnbindOnDisable" flag would be a perfectly elegant solution to this very use-case centred issue.
